#!/usr/bin/env python3
"""Vendor the turtle_body contract into this repo.

turtle_body (`../turtle_body`, the upstream geometry source — see CLAUDE.md
"Turtle Generator" and that repo's CLAUDE.md section 19) ships two things this
generator needs to stay in step with:

  * `build/params.json` — every `lib/params.scad` `p_*()` value plus the version,
    regenerated by `build/build.py` (turtle_body `build/export_params.py`).
  * `v1.0 SCADs/*.scad` — the four self-contained wooden-component bundles.

This script copies them into `generator/turtle_body/` and stamps the version.
Nothing here evaluates geometry; it is a pure copy + a diff. Run it after an
upstream release, then run `generator/check_params_sync.py` and review the diff.

    generator/sync_from_turtle_body.py                 # copy in place
    generator/sync_from_turtle_body.py --check         # exit nonzero if stale
    generator/sync_from_turtle_body.py --turtle-body /path/to/turtle_body

The upstream path defaults to `$TURTLE_BODY_DIR`, then `../turtle_body`.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent            # .../generator
VENDOR = HERE / "turtle_body"                     # where the copies land

PARAMS_SRC = "build/params.json"
BUNDLE_SRC_DIR = "v1.0 SCADs"
BUNDLES = (
    "Turtle_Core_Ecojoiner_v1.scad",
    "Turtle_Rear_Fin_v1.scad",
    "Turtle_Bottom_Ballast_Fin_v1.scad",
    "Turtle_Sail_Apparatus_v1.scad",
)


def _resolve_upstream(cli_value: str | None) -> Path:
    for candidate in (cli_value, os.environ.get("TURTLE_BODY_DIR"), HERE.parent.parent / "turtle_body"):
        if not candidate:
            continue
        path = Path(candidate).expanduser().resolve()
        if (path / PARAMS_SRC).is_file():
            return path
    raise SystemExit(
        "sync_from_turtle_body: could not find turtle_body. Pass --turtle-body "
        "PATH, set $TURTLE_BODY_DIR, or check out ../turtle_body and run "
        "`python3 build/build.py` there first (it writes build/params.json)."
    )


def _planned_copies(upstream: Path) -> list[tuple[Path, Path]]:
    pairs = [(upstream / PARAMS_SRC, VENDOR / "params.json")]
    for name in BUNDLES:
        pairs.append((upstream / BUNDLE_SRC_DIR / name, VENDOR / "scad" / name))
    return pairs


def _version_of(params_json: Path) -> str:
    import json

    return str(json.loads(params_json.read_text(encoding="utf-8")).get("version", "unknown"))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--turtle-body", dest="turtle_body", help="path to the turtle_body checkout")
    ap.add_argument("--check", action="store_true", help="report staleness, copy nothing")
    args = ap.parse_args(argv)

    upstream = _resolve_upstream(args.turtle_body)
    pairs = _planned_copies(upstream)

    missing = [str(src) for src, _ in pairs if not src.is_file()]
    if missing:
        raise SystemExit(
            "sync_from_turtle_body: upstream is missing files (run `python3 "
            "build/build.py` in turtle_body first):\n  " + "\n  ".join(missing)
        )

    stale: list[str] = []
    for src, dst in pairs:
        new = src.read_bytes()
        old = dst.read_bytes() if dst.is_file() else None
        if new == old:
            continue
        stale.append(str(dst.relative_to(HERE.parent)))
        if not args.check:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(new)

    vendored_params = VENDOR / "params.json"
    version = _version_of(vendored_params if vendored_params.is_file() else pairs[0][0])
    version_file = VENDOR / "VERSION"
    version_line = f"turtle_body {version}\n"
    current_version_line = (
        version_file.read_text(encoding="utf-8") if version_file.is_file() else ""
    )
    if current_version_line != version_line:
        stale.append(str(version_file.relative_to(HERE.parent)))
        if not args.check:
            version_file.write_text(version_line, encoding="utf-8")

    if not stale:
        print(f"in sync with turtle_body {version}  ({upstream})")
        return 0
    if args.check:
        print("STALE vs turtle_body — run: python3 generator/sync_from_turtle_body.py")
        for s in stale:
            print(f"  {s}")
        return 1
    print(f"synced to turtle_body {version}  ({upstream})")
    for s in stale:
        print(f"  updated {s}")
    print("\nNow run: python3 generator/check_params_sync.py  and review `git diff generator/turtle_body/`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
