#!/usr/bin/env python3
"""
Ecojoiner v3.2 export generator
================================

Generates backend-ready Ecojoiner files from bottle + wood measurements:
  - Letter landscape PDF carpenter sheet
  - Self-contained OpenSCAD .scad file
  - 1:1 SVG cutting files
  - 1:1 DXF cutting files
  - JSON manifest with inputs, derived dimensions, and exported file paths

Current design logic: Flatpack Ecojoiner v3.2
  - Long John x 6
  - Little John x 5
  - Master John x 1
  - Final Key x 4
  - Presser x 12

Important design notes:
  - Saddlers have been removed and replaced by four Final Keys.
  - John's central holes are all the same diameter by default. The script still
    accepts cap_diameter and collar_diameter because the form collects both.
  - John screw holes are M6 pilot holes: cut as diameter 4.5mm so the screw
    thread can bite into wood.
  - Pressers use a through M6 pilot hole, plus a top nut recess:
      * through hole: diameter 4.5mm through
      * nut recess: diameter 10mm x 5mm deep

Expected backend usage:
  1. Receive POST fields from /ecojoiners/generate.
  2. Pass the values into this script as CLI args or import this module.
  3. Save generated files under public/ecojoiner_exports/<job-slug>/.
  4. Return download URLs to the frontend.

This file is intentionally verbose and well-commented so it can be adapted
cleanly into an Express, Nuxt/Nitro, Flask, FastAPI, or other backend.
"""

from __future__ import annotations

import argparse
import html
import json
import math
import os
import re
import sys
import uuid
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

# ReportLab is used only for PDF generation. SVG and SCAD generation use only
# Python's standard library.
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import landscape, letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.pdfgen import canvas
    from reportlab.platypus import Paragraph
except Exception:  # pragma: no cover - useful in backend deployments
    colors = None
    letter = None
    mm = None
    canvas = None
    Paragraph = None
    ParagraphStyle = None
    getSampleStyleSheet = None
    pdfmetrics = None
    TTFont = None

# ezdxf is used only for DXF generation. SVG and SCAD generation use only
# Python's standard library.
try:
    import ezdxf
except Exception:  # pragma: no cover - useful in backend deployments
    ezdxf = None


# ---------------------------------------------------------------------------
# Constants and defaults
# ---------------------------------------------------------------------------

DESIGN_VERSION = "3.2"
LICENSE_ID = "CERN-OHL-S-2.0"
DEFAULT_PORT_ALLOWANCE_MM = 20.0

VISION_STATEMENT = (
    "The ecojoiner is shared freely with the world to help people everywhere "
    "design, build, and innovate with bottles and wood - creating furniture, "
    "structures, shelters, and anything else that helps make life on Earth greener "
    "for humans, creatures, and the ecosystems we share. Derivatives and future "
    "versions should carry the Ecojoiner name, credit ecobricks.org, and be shared "
    "reciprocally under the same CERN-OHL-S-2.0 license."
)

LICENSE_STATEMENT = (
    "This autogenerated ecojoiner design is developed and shared under the CERN "
    "Open Hardware Licence, Strongly Reciprocal license (CERN-OHL-S-2.0)."
)

# Part quantities for the v3.2 flatpack.
PART_QUANTITIES = {
    "Long John": 6,
    "Little John": 5,
    "Master John": 1,
    "Final Key": 4,
    "Presser": 12,
}


# ---------------------------------------------------------------------------
# PDF text translations
# ---------------------------------------------------------------------------
# The generated PDF is the only export with prose/labels baked into it (SVG
# and DXF only carry part names like "Long John 3", which — like the
# `gen_part_*` locale keys the frontend uses for the same names — are kept in
# English in every language, matching the site's existing convention).
# Site language codes not listed here fall back to English; part names,
# units (mm), and screw callouts (M6) are not translated anywhere.
SUPPORTED_PDF_LANGS = ("en", "id", "tr")

PDF_STRINGS: Dict[str, Dict[str, str]] = {
    "vision_statement": {
        "en": VISION_STATEMENT,
        "id": (
            "Ecojoiner dibagikan secara bebas kepada dunia untuk membantu orang-orang di mana "
            "pun merancang, membangun, dan berinovasi dengan botol dan kayu - menciptakan mebel, "
            "struktur, tempat berlindung, dan apa pun yang membuat kehidupan di Bumi lebih hijau "
            "bagi manusia, makhluk hidup, dan ekosistem yang kita bagi bersama. Turunan dan versi "
            "mendatang harus tetap memakai nama Ecojoiner, mencantumkan kredit untuk ecobricks.org, "
            "dan dibagikan secara timbal balik di bawah lisensi CERN-OHL-S-2.0 yang sama."
        ),
        "tr": (
            "Ecojoiner, insanların şişe ve ahşap kullanarak mobilya, yapı, barınak ve Dünya'daki "
            "yaşamı insanlar, canlılar ve paylaştığımız ekosistemler için daha yeşil kılan her şeyi "
            "tasarlamasına, inşa etmesine ve yenilik yapmasına yardımcı olmak için dünyayla özgürce "
            "paylaşılmaktadır. Türevler ve gelecek sürümler Ecojoiner adını taşımalı, ecobricks.org'u "
            "kaynak göstermeli ve aynı CERN-OHL-S-2.0 lisansı altında karşılıklı olarak paylaşılmalıdır."
        ),
    },
    "license_statement": {
        "en": LICENSE_STATEMENT,
        "id": (
            "Desain ecojoiner yang dibuat otomatis ini dikembangkan dan dibagikan di bawah CERN "
            "Open Hardware Licence, Strongly Reciprocal license (CERN-OHL-S-2.0)."
        ),
        "tr": (
            "Bu otomatik oluşturulan ecojoiner tasarımı, CERN Açık Donanım Lisansı, Güçlü Karşılıklı "
            "lisans (CERN-OHL-S-2.0) kapsamında geliştirilmiş ve paylaşılmıştır."
        ),
    },
    "board_thickness": {
        "en": "Board Thickness for this ecojoiner set at {thickness} mm",
        "id": "Ketebalan Papan untuk set ecojoiner ini diatur ke {thickness} mm",
        "tr": "Bu ecojoiner seti için Tahta Kalınlığı {thickness} mm olarak ayarlandı",
    },
    "input_variables_title": {
        "en": "Input variables",
        "id": "Variabel input",
        "tr": "Girdi değişkenleri",
    },
    "derived_dimensions_title": {
        "en": "Derived dimensions",
        "id": "Dimensi turunan",
        "tr": "Türetilmiş ölçüler",
    },
    "wood": {
        "en": "Wood: {value}mm",
        "id": "Kayu: {value}mm",
        "tr": "Ahşap: {value}mm",
    },
    "port_length_line": {
        "en": "Port length: {value}mm",
        "id": "Panjang port: {value}mm",
        "tr": "Port uzunluğu: {value}mm",
    },
    "bottle_diameter": {
        "en": "Bottle diameter: {value}mm",
        "id": "Diameter botol: {value}mm",
        "tr": "Şişe çapı: {value}mm",
    },
    "cap_line": {
        "en": "Cap: ⌀{value}mm",
        "id": "Tutup: ⌀{value}mm",
        "tr": "Kapak: ⌀{value}mm",
    },
    "collar_line": {
        "en": "Collar: ⌀{value}mm",
        "id": "Kerah: ⌀{value}mm",
        "tr": "Yaka: ⌀{value}mm",
    },
    "fit_clearance_line": {
        "en": "Fit clearance: {value}mm",
        "id": "Toleransi pas: {value}mm",
        "tr": "Geçme boşluğu: {value}mm",
    },
    "john_dim": {
        "en": "John: {length} x {height}mm",
        "id": "John: {length} x {height}mm",
        "tr": "John: {length} x {height}mm",
    },
    "slot_width_line": {
        "en": "Slot width: {value}mm",
        "id": "Lebar slot: {value}mm",
        "tr": "Yuva genişliği: {value}mm",
    },
    "std_slot_depth_line": {
        "en": "Std slot depth: {value}mm",
        "id": "Kedalaman slot standar: {value}mm",
        "tr": "Standart yuva derinliği: {value}mm",
    },
    "master_slot_depth_line": {
        "en": "Master slot depth: {value}mm",
        "id": "Kedalaman slot master: {value}mm",
        "tr": "Ana yuva derinliği: {value}mm",
    },
    "final_key_dim": {
        "en": "Final Key: {length} x {width}mm",
        "id": "Final Key: {length} x {width}mm",
        "tr": "Final Key: {length} x {width}mm",
    },
    "presser_dim": {
        "en": "Presser: ⌀{value}mm",
        "id": "Presser: ⌀{value}mm",
        "tr": "Presser: ⌀{value}mm",
    },
    "notes": {
        "en": (
            "Note: This one-page PDF is a scaled carpenter reference. Use the SVG file for 1:1 digital cutting geometry. "
            "Cut order suggestion: inner holes and slots first; outer profiles last. CNC router users may need dogbone slot reliefs."
        ),
        "id": (
            "Catatan: PDF satu halaman ini adalah referensi tukang kayu berskala. Gunakan file SVG untuk geometri "
            "pemotongan digital 1:1. Saran urutan potong: lubang dan slot bagian dalam terlebih dahulu; profil luar "
            "terakhir. Pengguna router CNC mungkin memerlukan pelonggaran slot dogbone."
        ),
        "tr": (
            "Not: Bu tek sayfalık PDF, ölçekli bir marangoz referansıdır. 1:1 dijital kesim geometrisi için SVG "
            "dosyasını kullanın. Kesim sırası önerisi: önce iç delikler ve yuvalar; en son dış profiller. CNC router "
            "kullanıcılarının dogbone yuva rahatlatmalarına ihtiyacı olabilir."
        ),
    },
    "port_label": {
        "en": "port {value}mm",
        "id": "port {value}mm",
        "tr": "port {value}mm",
    },
    "between_notches_label": {
        "en": "{value}mm (bottle ⌀)",
        "id": "{value}mm (⌀ botol)",
        "tr": "{value}mm (şişe ⌀)",
    },
    "slot_label": {
        "en": "slot {value}mm",
        "id": "slot {value}mm",
        "tr": "yuva {value}mm",
    },
    "from_side_label": {
        "en": "25mm from side",
        "id": "25mm dari sisi",
        "tr": "kenardan 25mm",
    },
    "through_hole_label": {
        "en": "M6 through-hole: ⌀{value}mm",
        "id": "Lubang tembus M6: ⌀{value}mm",
        "tr": "M6 geçme deliği: ⌀{value}mm",
    },
    "nut_recess_label": {
        "en": "nut recess: ⌀{diam}mm x {depth}mm deep",
        "id": "dudukan mur: ⌀{diam}mm x {depth}mm dalam",
        "tr": "somun yuvası: ⌀{diam}mm x {depth}mm derinlik",
    },
    "version_credit": {
        "en": "Version {version} of the Ecojoiner. Invention by Russell Maier. Engineering by Richard Graham. See ecobricks.org/ecojoiner.",
        "id": "Versi {version} dari Ecojoiner. Ditemukan oleh Russell Maier. Direkayasa oleh Richard Graham. Lihat ecobricks.org/ecojoiner.",
        "tr": "Ecojoiner'ın {version} sürümü. Russell Maier tarafından icat edildi. Richard Graham tarafından mühendisliği yapıldı. ecobricks.org/ecojoiner adresine bakın.",
    },
}


def _pdf_lang(inputs: "EcojoinerInputs") -> str:
    lang = (getattr(inputs, "lang", "en") or "en").lower()
    return lang if lang in SUPPORTED_PDF_LANGS else "en"


# Arvo (the title font) has no glyphs for Turkish ş/ğ/İ, so translated text
# drawn in the title style falls back to Mulish (the body font, which does)
# for Turkish specifically. Indonesian and English need no such fallback.
TITLE_FONT_UNSUPPORTED_LANGS = {"tr"}


def _title_font_for(lang: str, title_font: str, body_font: str) -> str:
    return body_font if lang in TITLE_FONT_UNSUPPORTED_LANGS else title_font


def T(lang: str, key: str, **kwargs) -> str:
    """Look up a PDF string in `lang`, falling back to English, then format it."""
    entry = PDF_STRINGS.get(key, {})
    template = entry.get(lang) or entry.get("en") or key
    return template.format(**kwargs) if kwargs else template


def _ceil_mm(value: float) -> int:
    """Round a millimetre dimension up to the nearest whole mm for the PDF.

    The PDF is a scaled carpenter reference (the SVG/DXF carry the exact 1:1
    geometry), and carpenters work off a tape measure with mm graduations —
    rounding down could leave a part fractionally short, so every displayed
    dimension rounds up instead. `round(value, 6)` first absorbs float noise
    (e.g. 12.000000001) so it doesn't get bumped up to the next mm.
    """
    return int(math.ceil(round(value, 6)))


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EcojoinerInputs:
    """Raw values collected from the frontend form, after parsing.

    Field mapping from the current frontend form:
      - wood thickness -> slat_thickness
      - bottle cap diameter -> cap_diameter
      - bottle collar diameter -> collar_diameter
      - bottle taper height -> taper_height
      - bottle diameter -> port_height
      - bottle volume -> bottle_volume_l
      - bottle brand -> bottle_brand
      - selected formats -> formats

    The backend may provide port_length directly. If port_length is omitted,
    this script calculates it as:
        port_length = taper_height + port_allowance

    port_height already has the "Adjust Connection" fit offset folded in by
    parse_inputs_from_dict() / main() — see port_fit_mm there. Nothing past
    parsing needs to know about the offset separately; it's just a tighter
    (or looser) port_height.
    """

    slat_thickness: float = 12.0
    cap_diameter: float = 32.0
    collar_diameter: float = 32.0
    taper_height: Optional[float] = 60.0
    port_length: Optional[float] = None
    port_allowance: float = DEFAULT_PORT_ALLOWANCE_MM
    port_height: float = 85.0  # bottle body diameter
    bottle_volume_l: float = 1.5
    bottle_brand: str = "generic"
    screw_diameter: float = 4.5  # physical pilot-hole diameter
    screw_label: str = "M6 (diameter 4.5mm)"
    fit_clearance: float = 0.20
    formats: Tuple[str, ...] = ("pdf", "scad", "svg")
    job_id: str = ""
    lang: str = "en"  # site language; see PDF_STRINGS/_pdf_lang for supported codes


@dataclass(frozen=True)
class EcojoinerDerived:
    """Dimensions derived from the form inputs.

    These values should be displayed in the frontend before download, because
    they let the user catch bad bottle or board measurements early.
    """

    port_length: float
    john_length: float
    john_height: float
    slot_width: float
    standard_slot_depth: float
    master_slot_depth: float
    long_end_span: float
    long_center_span: float
    little_end_span: float
    little_center_span: float
    screw_side_offset: float
    screw_y_center: float
    final_key_length: float
    final_key_width: float
    presser_diameter: float
    presser_thickness: float
    presser_through_hole_diameter: float
    presser_nut_recess_diameter: float
    presser_nut_recess_depth: float


@dataclass(frozen=True)
class GeneratedFile:
    format: str
    label: str
    path: str
    url: str


# ---------------------------------------------------------------------------
# Parsing, validation, derived dimensions, and naming
# ---------------------------------------------------------------------------

def _to_float(value, default: Optional[float] = None) -> Optional[float]:
    """Convert form values to float while tolerating empty strings."""
    if value is None or value == "":
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        raise ValueError(f"Expected a number, got {value!r}")


def _slugify(text: str, fallback: str = "generic") -> str:
    """Create a safe filename slug from user-provided brand text."""
    text = (text or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    return text or fallback


def parse_inputs_from_dict(data: Dict[str, object]) -> EcojoinerInputs:
    """Parse frontend POST/JSON data into EcojoinerInputs.

    This function accepts both camelCase names used in JS forms and snake_case
    names used by Python/SCAD. That makes it easier to wire into different
    backend frameworks.
    """

    def get(*names, default=None):
        for name in names:
            if name in data:
                return data[name]
        return default

    raw_formats = get("formats", "exportFormats", default=("pdf", "scad", "svg"))
    if isinstance(raw_formats, str):
        # Works for comma-separated values from JSON or a single checkbox value.
        formats = tuple(x.strip().lower() for x in raw_formats.split(",") if x.strip())
    elif isinstance(raw_formats, Iterable):
        formats = tuple(str(x).strip().lower() for x in raw_formats if str(x).strip())
    else:
        formats = ("pdf", "scad", "svg")

    return EcojoinerInputs(
        slat_thickness=_to_float(get("slatThickness", "slat_thickness"), 12.0),
        cap_diameter=_to_float(get("capDiameter", "cap_diameter"), 32.0),
        collar_diameter=_to_float(get("collarDiameter", "collar_diameter"), 32.0),
        taper_height=_to_float(get("taperHeight", "taper_height"), None),
        port_length=_to_float(get("portLength", "port_length"), None),
        port_allowance=_to_float(get("portAllowance", "port_allowance"), DEFAULT_PORT_ALLOWANCE_MM),
        port_height=_to_float(get("portHeight", "port_height", "bottleDiameter", "bottle_diameter"), 85.0)
        + _to_float(get("portFitMm", "port_fit_mm"), 0.0),
        bottle_volume_l=_to_float(get("bottleVolumeL", "bottle_volume_l", "volume", "bottleVolume"), 1.5),
        bottle_brand=str(get("bottleBrand", "bottle_brand", "brand", default="generic") or "generic"),
        screw_diameter=_to_float(get("screwDiameter", "screw_diameter"), 4.5),
        fit_clearance=_to_float(get("fitClearance", "fit_clearance"), 0.20),
        formats=formats,
        job_id=str(get("jobId", "job_id", default="") or ""),
        lang=str(get("lang", default="en") or "en").lower(),
    )


def validate_inputs(inputs: EcojoinerInputs) -> List[str]:
    """Return a list of validation errors. Empty list means OK."""

    errors: List[str] = []

    # Calculate port_length for validation.
    port_length = inputs.port_length
    if port_length is None:
        if inputs.taper_height is None:
            errors.append("Provide either port_length or taper_height.")
            port_length = 0
        else:
            port_length = inputs.taper_height + inputs.port_allowance

    def in_range(label: str, value: float, low: float, high: float, unit: str = "mm"):
        if value < low or value > high:
            errors.append(f"{label} must be between {low:g} and {high:g} {unit}.")

    in_range("Wood thickness", inputs.slat_thickness, 3, 30)
    in_range("Port length", port_length, 20, 200)
    in_range("Bottle diameter / port height", inputs.port_height, 30, 200)
    in_range("Cap diameter", inputs.cap_diameter, 10, 80)
    in_range("Collar diameter", inputs.collar_diameter, 10, 90)
    in_range("Screw pilot-hole diameter", inputs.screw_diameter, 3, 12)
    in_range("Fit clearance", inputs.fit_clearance, 0, 2)

    if inputs.bottle_volume_l <= 0 or inputs.bottle_volume_l > 5:
        errors.append("Bottle volume must be greater than 0L and no more than 5L.")

    # Geometry-specific sanity checks.
    john_height = inputs.port_height - 2 * inputs.slat_thickness
    if john_height <= 0:
        errors.append("Bottle diameter must be greater than twice the wood thickness.")
    else:
        # Keep real material around cap/collar holes. This is a practical
        # woodworking safety margin, not a mathematical requirement.
        min_material_mm = 4.0
        if inputs.cap_diameter >= john_height:
            errors.append("Cap hole is too large for the calculated John slat height.")
        if inputs.collar_diameter >= john_height:
            errors.append("Collar hole is too large for the calculated John slat height.")
        if inputs.screw_diameter >= john_height:
            errors.append("Screw pilot hole is too large for the calculated John slat height.")
        if (john_height - inputs.cap_diameter) / 2 < min_material_mm:
            errors.append("Cap hole leaves less than 4mm of material above/below the hole.")
        if (john_height - inputs.collar_diameter) / 2 < min_material_mm:
            errors.append("Collar hole leaves less than 4mm of material above/below the hole.")

    allowed_formats = {"pdf", "scad", "svg", "dxf"}
    unknown_formats = [f for f in inputs.formats if f not in allowed_formats]
    if unknown_formats:
        errors.append(
            "Unsupported export format(s): " + ", ".join(unknown_formats) +
            ". This Python generator currently supports pdf, scad, svg, and dxf."
        )

    return errors


def derive_dimensions(inputs: EcojoinerInputs) -> EcojoinerDerived:
    """Calculate all geometry from user inputs.

    These formulas are the backbone of the Ecojoiner generator and should stay
    in sync with the OpenSCAD core module used by the website.
    """

    port_length = inputs.port_length
    if port_length is None:
        if inputs.taper_height is None:
            raise ValueError("Cannot derive port_length without taper_height.")
        port_length = inputs.taper_height + inputs.port_allowance

    slat = inputs.slat_thickness
    port_height = inputs.port_height

    john_height = port_height - 2 * slat
    john_length = 2 * port_length + port_height + 4 * slat
    slot_width = slat + inputs.fit_clearance

    # In the Johns, slots are cut downward from the top edge.
    standard_slot_depth = math.ceil(john_height / 2)
    master_slot_depth = math.floor(port_height / 2)

    # Internal spans for Long John vs Little/Master John.
    long_end_span = port_length
    long_center_span = port_height + 2 * slat
    little_end_span = port_length + slat
    little_center_span = port_height

    # M6 pilot holes: centered vertically, fixed 25mm from side edges.
    screw_side_offset = 25.0
    screw_y_center = john_height / 2

    # Final Keys replace Saddlers in v3.2.
    final_key_length = port_height + 4 * slat
    final_key_width = 2 * slat

    # Presser: remnant from cap hole, allowing about 1mm saw/kerf loss.
    # For a 32mm cap hole, this gives the familiar 31mm Presser.
    presser_diameter = max(1.0, inputs.cap_diameter - 1.0)

    return EcojoinerDerived(
        port_length=port_length,
        john_length=john_length,
        john_height=john_height,
        slot_width=slot_width,
        standard_slot_depth=standard_slot_depth,
        master_slot_depth=master_slot_depth,
        long_end_span=long_end_span,
        long_center_span=long_center_span,
        little_end_span=little_end_span,
        little_center_span=little_center_span,
        screw_side_offset=screw_side_offset,
        screw_y_center=screw_y_center,
        final_key_length=final_key_length,
        final_key_width=final_key_width,
        presser_diameter=presser_diameter,
        presser_thickness=slat,
        presser_through_hole_diameter=inputs.screw_diameter,
        presser_nut_recess_diameter=10.0,
        presser_nut_recess_depth=5.0,
    )


def make_job_slug(inputs: EcojoinerInputs, derived: EcojoinerDerived) -> str:
    """Return ecojoiner_<brand>_<volume>L_<johnLength>x<johnHeight>_<jobId>."""
    brand = _slugify(inputs.bottle_brand)
    volume = str(inputs.bottle_volume_l).replace(".", "p")
    job_id = _slugify(inputs.job_id or uuid.uuid4().hex[:8], fallback=uuid.uuid4().hex[:8])
    return (
        f"ecojoiner_{brand}_{volume}L_"
        f"{round(derived.john_length):g}x{round(derived.john_height):g}_{job_id}"
    )


# ---------------------------------------------------------------------------
# SVG helpers
# ---------------------------------------------------------------------------

def _svg_header(width_mm: float, height_mm: float) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width_mm:.3f}mm" height="{height_mm:.3f}mm" '
        f'viewBox="0 0 {width_mm:.3f} {height_mm:.3f}">\n'
        f'  <desc>Flatpack Ecojoiner v{DESIGN_VERSION}, 1:1 millimetre geometry</desc>\n'
        f'  <style>\n'
        f'    .cut {{ fill: none; stroke: #000000; stroke-width: 0.10; }}\n'
        f'    .mark {{ fill: none; stroke: #555555; stroke-width: 0.10; stroke-dasharray: 1 1; }}\n'
        f'    .label {{ font-family: sans-serif; font-size: 5px; fill: #333333; }}\n'
        f'  </style>\n'
    )


def _rect(x: float, y: float, w: float, h: float, klass: str = "cut") -> str:
    return f'  <rect class="{klass}" x="{x:.3f}" y="{y:.3f}" width="{w:.3f}" height="{h:.3f}"/>\n'


def _circle(cx: float, cy: float, d: float, klass: str = "cut") -> str:
    r = d / 2
    return f'  <circle class="{klass}" cx="{cx:.3f}" cy="{cy:.3f}" r="{r:.3f}"/>\n'


def _label(x: float, y: float, text: str) -> str:
    return f'  <text class="label" x="{x:.3f}" y="{y:.3f}">{html.escape(text)}</text>\n'


def _john_svg_group(
    name: str,
    x: float,
    y: float,
    inputs: EcojoinerInputs,
    d: EcojoinerDerived,
    slot_depth: float,
    slot_centres: Tuple[float, float],
    center_hole_diameter: float,
    include_labels: bool = True,
) -> str:
    """SVG group for one John slat.

    SVG uses independent paths/objects. CAM software can interpret these as
    inner/outer cuts. Use inner cuts before outer cuts in the CAM workflow.
    """
    out = f'  <g id="{html.escape(name.lower().replace(" ", "_"))}" transform="translate({x:.3f} {y:.3f})">\n'
    out += _rect(0, 0, d.john_length, d.john_height, "cut")

    # Slots are shown as cut rectangles inside the outer slat profile.
    for cx in slot_centres:
        out += _rect(cx - d.slot_width / 2, 0, d.slot_width, slot_depth, "cut")

    out += _circle(d.john_length / 2, d.john_height / 2, center_hole_diameter, "cut")
    out += _circle(d.screw_side_offset, d.screw_y_center, inputs.screw_diameter, "cut")
    out += _circle(d.john_length - d.screw_side_offset, d.screw_y_center, inputs.screw_diameter, "cut")

    if include_labels:
        out += _label(0, -3, name)
    out += "  </g>\n"
    return out


def write_svg(path: Path, inputs: EcojoinerInputs, d: EcojoinerDerived, *, full_set: bool = True) -> None:
    """Write a 1:1 SVG cutting file.

    full_set=True creates all required quantities. full_set=False creates one
    of each part as a compact preview/cut test.
    """

    gap = 12.0
    margin = 10.0
    row_h = max(d.john_height, d.final_key_width, d.presser_diameter) + gap

    # Estimate a simple row-based layout. This is clean, not material-optimized.
    if full_set:
        rows = PART_QUANTITIES["Long John"] + PART_QUANTITIES["Little John"] + PART_QUANTITIES["Master John"]
        width = margin * 2 + d.john_length
        height = margin * 2 + rows * row_h + 2 * row_h
    else:
        width = margin * 2 + d.john_length + gap + max(d.final_key_length, d.presser_diameter)
        height = margin * 2 + 3 * row_h

    out = _svg_header(width, height)
    out += f'  <metadata>{html.escape(json.dumps({"version": DESIGN_VERSION, "license": LICENSE_ID}))}</metadata>\n'

    y = margin
    long_slots = (
        d.long_end_span + inputs.slat_thickness / 2,
        d.john_length - d.long_end_span - inputs.slat_thickness / 2,
    )
    little_slots = (
        d.little_end_span + inputs.slat_thickness / 2,
        d.john_length - d.little_end_span - inputs.slat_thickness / 2,
    )

    if full_set:
        for i in range(PART_QUANTITIES["Long John"]):
            out += _john_svg_group(f"Long John {i+1}", margin, y, inputs, d, d.standard_slot_depth, long_slots, inputs.cap_diameter)
            y += row_h
        for i in range(PART_QUANTITIES["Little John"]):
            out += _john_svg_group(f"Little John {i+1}", margin, y, inputs, d, d.standard_slot_depth, little_slots, inputs.collar_diameter)
            y += row_h
        out += _john_svg_group("Master John", margin, y, inputs, d, d.master_slot_depth, little_slots, inputs.collar_diameter)
        y += row_h

        # Final Keys on one row.
        x = margin
        for i in range(PART_QUANTITIES["Final Key"]):
            out += f'  <g id="final_key_{i+1}" transform="translate({x:.3f} {y:.3f})">\n'
            out += _rect(0, 0, d.final_key_length, d.final_key_width, "cut")
            out += _label(0, -3, f"Final Key {i+1}")
            out += "  </g>\n"
            x += d.final_key_length + gap
        y += row_h

        # Pressers on one or more rows. Main circle, through hole, and nut recess mark.
        x = margin
        for i in range(PART_QUANTITIES["Presser"]):
            if x + d.presser_diameter > width - margin:
                x = margin
                y += d.presser_diameter + gap
            out += f'  <g id="presser_{i+1}" transform="translate({x:.3f} {y:.3f})">\n'
            out += _circle(d.presser_diameter / 2, d.presser_diameter / 2, d.presser_diameter, "cut")
            out += _circle(d.presser_diameter / 2, d.presser_diameter / 2, d.presser_through_hole_diameter, "cut")
            out += _circle(d.presser_diameter / 2, d.presser_diameter / 2, d.presser_nut_recess_diameter, "mark")
            out += _label(0, -3, f"Presser {i+1}")
            out += "  </g>\n"
            x += d.presser_diameter + gap
    else:
        out += _john_svg_group("Long John x6", margin, y, inputs, d, d.standard_slot_depth, long_slots, inputs.cap_diameter)
        y += row_h
        out += _john_svg_group("Little John x5", margin, y, inputs, d, d.standard_slot_depth, little_slots, inputs.collar_diameter)
        y += row_h
        out += _john_svg_group("Master John x1", margin, y, inputs, d, d.master_slot_depth, little_slots, inputs.collar_diameter)
        # Final key and presser column.
        x2 = margin + d.john_length + gap
        out += f'  <g id="final_key" transform="translate({x2:.3f} {margin:.3f})">\n'
        out += _rect(0, 0, d.final_key_length, d.final_key_width, "cut")
        out += _label(0, -3, "Final Key x4")
        out += "  </g>\n"
        out += f'  <g id="presser" transform="translate({x2:.3f} {margin + d.final_key_width + gap:.3f})">\n'
        out += _circle(d.presser_diameter / 2, d.presser_diameter / 2, d.presser_diameter, "cut")
        out += _circle(d.presser_diameter / 2, d.presser_diameter / 2, d.presser_through_hole_diameter, "cut")
        out += _circle(d.presser_diameter / 2, d.presser_diameter / 2, d.presser_nut_recess_diameter, "mark")
        out += _label(0, -3, "Presser x12")
        out += "  </g>\n"

    out += "</svg>\n"
    path.write_text(out, encoding="utf-8")


# ---------------------------------------------------------------------------
# DXF generation
# ---------------------------------------------------------------------------

DXF_CUT_LAYER = "CUT"
DXF_MARK_LAYER = "MARK"
DXF_LABEL_LAYER = "LABEL"


def _dxf_setup(doc) -> None:
    """Create the CUT/MARK/LABEL layers (and DASHED linetype) write_dxf() uses.

    Mirrors the SVG output's `.cut` (solid, real cut geometry) and `.mark`
    (dashed, non-cutting reference such as a nut recess) CSS classes.
    """
    if "DASHED" not in doc.linetypes:
        doc.linetypes.add("DASHED", pattern=[3.0, 2.0, -1.0])
    if DXF_CUT_LAYER not in doc.layers:
        doc.layers.add(DXF_CUT_LAYER, color=7)
    if DXF_MARK_LAYER not in doc.layers:
        doc.layers.add(DXF_MARK_LAYER, color=8, linetype="DASHED")
    if DXF_LABEL_LAYER not in doc.layers:
        doc.layers.add(DXF_LABEL_LAYER, color=3)


def _dxf_rect(msp, x: float, y: float, w: float, h: float, layer: str = DXF_CUT_LAYER) -> None:
    pline = msp.add_lwpolyline(
        [(x, y), (x + w, y), (x + w, y + h), (x, y + h)],
        dxfattribs={"layer": layer},
    )
    pline.closed = True


def _dxf_circle(msp, cx: float, cy: float, diameter: float, layer: str = DXF_CUT_LAYER) -> None:
    msp.add_circle(center=(cx, cy), radius=diameter / 2, dxfattribs={"layer": layer})


def _dxf_label(msp, x: float, y: float, text: str) -> None:
    msp.add_text(text, dxfattribs={"layer": DXF_LABEL_LAYER, "height": 2.5, "insert": (x, y)})


def _john_dxf_group(
    msp,
    name: str,
    x: float,
    y: float,
    inputs: EcojoinerInputs,
    d: EcojoinerDerived,
    slot_depth: float,
    slot_centres: Tuple[float, float],
    center_hole_diameter: float,
    include_labels: bool = True,
) -> None:
    """DXF equivalent of _john_svg_group: outer rect, slot rects, center hole,
    two screw pilot holes, and an optional label - all offset by (x, y).

    DXF has no `<g transform="translate()">` equivalent, so every coordinate
    below has (x, y) added directly rather than relying on a transform. Any
    geometry change ported over from _john_svg_group must add the offset by
    hand here too.
    """
    _dxf_rect(msp, x, y, d.john_length, d.john_height, DXF_CUT_LAYER)

    for cx in slot_centres:
        _dxf_rect(msp, x + cx - d.slot_width / 2, y, d.slot_width, slot_depth, DXF_CUT_LAYER)

    _dxf_circle(msp, x + d.john_length / 2, y + d.john_height / 2, center_hole_diameter, DXF_CUT_LAYER)
    _dxf_circle(msp, x + d.screw_side_offset, y + d.screw_y_center, inputs.screw_diameter, DXF_CUT_LAYER)
    _dxf_circle(
        msp, x + d.john_length - d.screw_side_offset, y + d.screw_y_center, inputs.screw_diameter, DXF_CUT_LAYER
    )

    if include_labels:
        _dxf_label(msp, x, y - 3, name)


def write_dxf(path: Path, inputs: EcojoinerInputs, d: EcojoinerDerived, *, full_set: bool = True) -> None:
    """Write a 1:1 DXF cutting file.

    A direct structural port of write_svg(): same margins, gaps, and
    full_set/one-each row layout, just emitting DXF entities instead of SVG
    element strings. Every cut/mark shape is an independent, non-boolean
    closed entity (LWPOLYLINE or CIRCLE), same as the SVG output - CAM
    software can interpret these as inner/outer cuts. Use inner cuts before
    outer cuts in the CAM workflow.
    """
    if ezdxf is None:
        raise RuntimeError("ezdxf is not installed. Install with: pip install ezdxf")

    doc = ezdxf.new(dxfversion="R2010")
    doc.units = ezdxf.units.MM
    _dxf_setup(doc)
    msp = doc.modelspace()

    gap = 12.0
    margin = 10.0
    row_h = max(d.john_height, d.final_key_width, d.presser_diameter) + gap

    y = margin
    long_slots = (
        d.long_end_span + inputs.slat_thickness / 2,
        d.john_length - d.long_end_span - inputs.slat_thickness / 2,
    )
    little_slots = (
        d.little_end_span + inputs.slat_thickness / 2,
        d.john_length - d.little_end_span - inputs.slat_thickness / 2,
    )

    if full_set:
        for i in range(PART_QUANTITIES["Long John"]):
            _john_dxf_group(
                msp, f"Long John {i+1}", margin, y, inputs, d, d.standard_slot_depth, long_slots, inputs.cap_diameter
            )
            y += row_h
        for i in range(PART_QUANTITIES["Little John"]):
            _john_dxf_group(
                msp, f"Little John {i+1}", margin, y, inputs, d, d.standard_slot_depth, little_slots, inputs.collar_diameter
            )
            y += row_h
        _john_dxf_group(
            msp, "Master John", margin, y, inputs, d, d.master_slot_depth, little_slots, inputs.collar_diameter
        )
        y += row_h

        # Final Keys on one row.
        x = margin
        for i in range(PART_QUANTITIES["Final Key"]):
            _dxf_rect(msp, x, y, d.final_key_length, d.final_key_width, DXF_CUT_LAYER)
            _dxf_label(msp, x, y - 3, f"Final Key {i+1}")
            x += d.final_key_length + gap
        y += row_h

        # Pressers on one or more rows, wrapping at the same width write_svg
        # uses for its full_set canvas.
        x = margin
        width_limit = margin * 2 + d.john_length
        for i in range(PART_QUANTITIES["Presser"]):
            if x + d.presser_diameter > width_limit - margin:
                x = margin
                y += d.presser_diameter + gap
            cx, cy = x + d.presser_diameter / 2, y + d.presser_diameter / 2
            _dxf_circle(msp, cx, cy, d.presser_diameter, DXF_CUT_LAYER)
            _dxf_circle(msp, cx, cy, d.presser_through_hole_diameter, DXF_CUT_LAYER)
            _dxf_circle(msp, cx, cy, d.presser_nut_recess_diameter, DXF_MARK_LAYER)
            _dxf_label(msp, x, y - 3, f"Presser {i+1}")
            x += d.presser_diameter + gap
    else:
        _john_dxf_group(
            msp, "Long John x6", margin, y, inputs, d, d.standard_slot_depth, long_slots, inputs.cap_diameter
        )
        y += row_h
        _john_dxf_group(
            msp, "Little John x5", margin, y, inputs, d, d.standard_slot_depth, little_slots, inputs.collar_diameter
        )
        y += row_h
        _john_dxf_group(
            msp, "Master John x1", margin, y, inputs, d, d.master_slot_depth, little_slots, inputs.collar_diameter
        )

        # Final key and presser column.
        x2 = margin + d.john_length + gap
        _dxf_rect(msp, x2, margin, d.final_key_length, d.final_key_width, DXF_CUT_LAYER)
        _dxf_label(msp, x2, margin - 3, "Final Key x4")

        presser_y = margin + d.final_key_width + gap
        cx, cy = x2 + d.presser_diameter / 2, presser_y + d.presser_diameter / 2
        _dxf_circle(msp, cx, cy, d.presser_diameter, DXF_CUT_LAYER)
        _dxf_circle(msp, cx, cy, d.presser_through_hole_diameter, DXF_CUT_LAYER)
        _dxf_circle(msp, cx, cy, d.presser_nut_recess_diameter, DXF_MARK_LAYER)
        _dxf_label(msp, x2, presser_y - 3, "Presser x12")

    doc.saveas(str(path))


# ---------------------------------------------------------------------------
# SCAD generation
# ---------------------------------------------------------------------------

def write_scad(path: Path, inputs: EcojoinerInputs, d: EcojoinerDerived) -> None:
    """Write a self-contained OpenSCAD file.

    This generated SCAD does not require a separate ecojoiner_core.scad file,
    which makes it better for user downloads. Your backend may still keep a
    separate core file for maintenance, but downloadable SCAD should be portable.
    """

    scad = f'''/*
  Flatpack Ecojoiner v{DESIGN_VERSION} - autogenerated
  License: {LICENSE_ID}

  Parts:
    Long John x 6
    Little John x 5
    Master John x 1
    Final Key x 4
    Presser x 12

  Generated from bottle/wood form inputs.
*/

$fn = 96;

// ---------- Input variables ----------
slat_thickness = {inputs.slat_thickness:.3f};
port_length = {d.port_length:.3f};
port_height = {inputs.port_height:.3f};  // bottle diameter
cap_diameter = {inputs.cap_diameter:.3f};
collar_diameter = {inputs.collar_diameter:.3f};
screw_diameter = {inputs.screw_diameter:.3f};  // M6 pilot hole cut diameter
fit_clearance = {inputs.fit_clearance:.3f};

// ---------- Display/export controls ----------
part = "layout";       // layout, full_set, long_john, little_john, master_john, final_key, presser
output_mode = "solid_3d"; // solid_3d or cut_2d
show_labels = true;
layout_gap = 24;
label_size = 7;
label_depth = 0.6;

// ---------- Derived dimensions ----------
john_height = port_height - 2 * slat_thickness;
john_length = 2 * port_length + port_height + 4 * slat_thickness;
slot_width = slat_thickness + fit_clearance;
standard_slot_depth = ceil(john_height / 2);
master_slot_depth = floor(port_height / 2);
long_end_span = port_length;
long_center_span = port_height + 2 * slat_thickness;
little_end_span = port_length + slat_thickness;
little_center_span = port_height;
screw_side_offset = 25;
screw_y_center = john_height / 2;
final_key_length = port_height + 4 * slat_thickness;
final_key_width = 2 * slat_thickness;
presser_diameter = max(1, cap_diameter - 1);
presser_through_hole_diameter = screw_diameter;
presser_nut_recess_diameter = 10;
presser_nut_recess_depth = 5;

// ---------- Safety checks ----------
assert(slat_thickness >= 3 && slat_thickness <= 30, "slat_thickness out of range");
assert(port_length >= 20 && port_length <= 200, "port_length out of range");
assert(port_height >= 30 && port_height <= 200, "port_height out of range");
assert(cap_diameter >= 10 && cap_diameter <= 80, "cap_diameter out of range");
assert(collar_diameter >= 10 && collar_diameter <= 90, "collar_diameter out of range");
assert(screw_diameter >= 3 && screw_diameter <= 12, "screw_diameter out of range");
assert(fit_clearance >= 0 && fit_clearance <= 2, "fit_clearance out of range");
assert(john_height > 0, "Bottle diameter must be greater than twice the wood thickness");
assert(cap_diameter < john_height, "Cap hole too large for John height");
assert(collar_diameter < john_height, "Collar hole too large for John height");

// ---------- Helper modules ----------
module maybe_extrude() {{
  if (output_mode == "cut_2d") children();
  else linear_extrude(height=slat_thickness) children();
}}

module top_slot(center_x, depth) {{
  translate([center_x - slot_width / 2, john_height - depth])
    square([slot_width, depth + 1], center=false);
}}

module center_hole(diameter) {{
  translate([john_length / 2, john_height / 2]) circle(d=diameter);
}}

module screw_holes_2d() {{
  translate([screw_side_offset, screw_y_center]) circle(d=screw_diameter);
  translate([john_length - screw_side_offset, screw_y_center]) circle(d=screw_diameter);
}}

module part_label(txt, w, h) {{
  if (show_labels && output_mode != "cut_2d")
    translate([w / 2, -label_size * 1.4, slat_thickness])
      linear_extrude(height=label_depth)
        text(txt, size=label_size, halign="center", valign="center");
}}

// ---------- 2D profiles ----------
module long_john_2d() {{
  difference() {{
    square([john_length, john_height], center=false);
    top_slot(long_end_span + slat_thickness / 2, standard_slot_depth);
    top_slot(john_length - long_end_span - slat_thickness / 2, standard_slot_depth);
    center_hole(cap_diameter);
    screw_holes_2d();
  }}
}}

module little_john_2d() {{
  difference() {{
    square([john_length, john_height], center=false);
    top_slot(little_end_span + slat_thickness / 2, standard_slot_depth);
    top_slot(john_length - little_end_span - slat_thickness / 2, standard_slot_depth);
    center_hole(collar_diameter);
    screw_holes_2d();
  }}
}}

module master_john_2d() {{
  difference() {{
    square([john_length, john_height], center=false);
    top_slot(little_end_span + slat_thickness / 2, master_slot_depth);
    top_slot(john_length - little_end_span - slat_thickness / 2, master_slot_depth);
    center_hole(collar_diameter);
    screw_holes_2d();
  }}
}}

module final_key_2d() {{
  square([final_key_length, final_key_width], center=false);
}}

module presser_2d() {{
  // Cutting view: outer circle and through pilot hole.
  difference() {{
    circle(d=presser_diameter);
    circle(d=presser_through_hole_diameter);
  }}
  // Nut recess is not a through-cut. It is shown as a faint reference circle.
  %circle(d=presser_nut_recess_diameter);
}}

// ---------- 3D parts ----------
module long_john() {{ maybe_extrude() long_john_2d(); part_label("Long John x 6", john_length, john_height); }}
module little_john() {{ maybe_extrude() little_john_2d(); part_label("Little John x 5", john_length, john_height); }}
module master_john() {{ maybe_extrude() master_john_2d(); part_label("Master John x 1", john_length, john_height); }}
module final_key() {{ maybe_extrude() final_key_2d(); part_label("Final Key x 4", final_key_length, final_key_width); }}

module presser() {{
  if (output_mode == "cut_2d") {{
    presser_2d();
  }} else {{
    // 3D view with through hole and top nut recess.
    difference() {{
      cylinder(d=presser_diameter, h=slat_thickness);
      translate([0,0,-0.1]) cylinder(d=presser_through_hole_diameter, h=slat_thickness + 0.2);
      translate([0,0,slat_thickness - presser_nut_recess_depth])
        cylinder(d=presser_nut_recess_diameter, h=presser_nut_recess_depth + 0.1);
    }}
    part_label("Presser x 12", presser_diameter, presser_diameter);
  }}
}}

// ---------- Layouts ----------
module one_each_layout() {{
  translate([0, 0, 0]) long_john();
  translate([0, -(john_height + layout_gap), 0]) little_john();
  translate([0, -2 * (john_height + layout_gap), 0]) master_john();
  translate([john_length + layout_gap, 0, 0]) final_key();
  translate([john_length + layout_gap + presser_diameter / 2, -(final_key_width + layout_gap + presser_diameter / 2), 0]) presser();
}}

module full_set_layout() {{
  row = john_height + layout_gap;
  for (i = [0:5]) translate([0, -i * row, 0]) long_john();
  for (i = [0:4]) translate([0, -(6+i) * row, 0]) little_john();
  translate([0, -11 * row, 0]) master_john();

  key_y = -12 * row;
  for (i = [0:3]) translate([i * (final_key_length + layout_gap), key_y, 0]) final_key();

  press_y = key_y - final_key_width - layout_gap - presser_diameter / 2;
  for (i = [0:11]) translate([presser_diameter/2 + i * (presser_diameter + layout_gap/2), press_y, 0]) presser();
}}

if (part == "layout") one_each_layout();
else if (part == "full_set") full_set_layout();
else if (part == "long_john") long_john();
else if (part == "little_john") little_john();
else if (part == "master_john") master_john();
else if (part == "final_key") final_key();
else if (part == "presser") presser();
else one_each_layout();
'''

    path.write_text(scad, encoding="utf-8")


# ---------------------------------------------------------------------------
# PDF generation
# ---------------------------------------------------------------------------

def _register_fonts(font_dir: Optional[Path] = None) -> Tuple[str, str, str]:
    """Register preferred fonts, falling back to DejaVu/Helvetica.

    Place fonts here if you want exact site typography:
      ecojoiner/fonts/Arvo-Regular.ttf
      ecojoiner/fonts/Mulish-Light.ttf
      ecojoiner/fonts/Mulish-Regular.ttf

    The fallback DejaVuSans is useful because it supports the diameter symbol.
    """
    if pdfmetrics is None:
        raise RuntimeError("ReportLab is not installed. Install with: pip install reportlab")

    search_dirs = []
    if font_dir:
        search_dirs.append(font_dir)
    search_dirs.extend([
        Path.cwd() / "ecojoiner" / "fonts",
        Path.cwd() / "fonts",
        Path("/usr/share/fonts/truetype/dejavu"),
    ])

    def try_font(font_name: str, filenames: Sequence[str]) -> Optional[str]:
        for directory in search_dirs:
            for filename in filenames:
                p = directory / filename
                if p.exists():
                    pdfmetrics.registerFont(TTFont(font_name, str(p)))
                    return font_name
        return None

    title_font = try_font("ArvoRegular", ["Arvo-Regular.ttf", "Arvo.ttf"])
    body_font = try_font("MulishLight", ["Mulish-Light.ttf", "Mulish-Regular.ttf"])
    mono_font = try_font("DejaVuSans", ["DejaVuSans.ttf"])

    # If preferred fonts are missing, use DejaVuSans so symbols like diameter render.
    fallback = mono_font or "Helvetica"
    return title_font or fallback, body_font or fallback, fallback


def _draw_dimension_line(c, x1, y1, x2, y2, text, font="Helvetica", size=7, offset=0, label_side="right", ext1=None, ext2=None, rotate_label=False):
    """Draw a simple dimension line with arrowheads and a label.

    The label's clearance from the line is computed from the label's own
    rendered width (for vertical lines) so it never visually crosses the
    line it's describing, regardless of how long the text is. `label_side`
    ("right" or "left") picks which side of a vertical line the label sits
    on, since the shape being dimensioned can be on either side of the line.

    `ext1`/`ext2`, when given as (x, y) points, are the actual feature edges
    the dimension line is measuring (the dimension line itself is often
    offset away from the geometry for legibility). A light witness/extension
    line is drawn from each feature edge out to the dimension line's
    endpoint so it is unambiguous what the arrow is pointing to.

    `rotate_label`, for vertical lines only, draws the label rotated 90
    degrees and centered directly on the line instead of offset to one
    side. Use this when the line runs through a narrow feature (like a
    slot) with no clear space beside it for a horizontal label.
    """
    if ext1 is not None or ext2 is not None:
        c.setStrokeColor(colors.HexColor("#cccccc"))
        c.setLineWidth(0.3)
        if ext1 is not None:
            c.line(ext1[0], ext1[1], x1, y1)
        if ext2 is not None:
            c.line(ext2[0], ext2[1], x2, y2)

    c.setStrokeColor(colors.HexColor("#777777"))
    c.setFillColor(colors.HexColor("#333333"))
    c.setLineWidth(0.5)
    c.line(x1, y1, x2, y2)

    # crude arrowheads; good enough for carpenter reference PDF. Scaled down
    # on very short lines (e.g. a small true-scale dimension like the
    # presser's nut-recess depth) so the two arrowheads don't cross over
    # each other and collide with the label text.
    line_len = math.hypot(x2 - x1, y2 - y1)
    ah = min(5, line_len / 3)
    c.setFont(font, size)
    text_w = c.stringWidth(text, font, size)
    if abs(x2 - x1) >= abs(y2 - y1):
        c.line(x1, y1, x1 + ah, y1 + ah / 2)
        c.line(x1, y1, x1 + ah, y1 - ah / 2)
        c.line(x2, y2, x2 - ah, y2 + ah / 2)
        c.line(x2, y2, x2 - ah, y2 - ah / 2)
        tx, ty = (x1 + x2) / 2, y1 + 5 + offset
    elif rotate_label:
        c.line(x1, y1, x1 + ah / 2, y1 + ah)
        c.line(x1, y1, x1 - ah / 2, y1 + ah)
        c.line(x2, y2, x2 + ah / 2, y2 - ah)
        c.line(x2, y2, x2 - ah / 2, y2 - ah)
        c.saveState()
        c.translate((x1 + x2) / 2, (y1 + y2) / 2)
        c.rotate(90)
        c.drawCentredString(0, 0, text)
        c.restoreState()
        return
    else:
        c.line(x1, y1, x1 + ah / 2, y1 + ah)
        c.line(x1, y1, x1 - ah / 2, y1 + ah)
        c.line(x2, y2, x2 + ah / 2, y2 - ah)
        c.line(x2, y2, x2 - ah / 2, y2 - ah)
        gap = text_w / 2 + 6 + offset
        tx = x1 - gap if label_side == "left" else x1 + gap
        ty = (y1 + y2) / 2 - size * 0.32

    c.drawCentredString(tx, ty, text)


def _draw_top_edge_with_gaps(c, x0, y_top, x1, gaps):
    """Draw a horizontal top edge as a set of segments, skipping over `gaps`.

    Each gap is an (start_x, end_x) pair in point coordinates where the slot
    notch is cut into the top edge, so that stretch of the edge is open
    material rather than a closed line.
    """
    segments_start = x0
    for gap_start, gap_end in sorted(gaps):
        if gap_start > segments_start:
            c.line(segments_start, y_top, gap_start, y_top)
        segments_start = max(segments_start, gap_end)
    if segments_start < x1:
        c.line(segments_start, y_top, x1, y_top)


def _rounded_rect_text(c, x, y, w, h, title, lines, title_font, body_font):
    c.setStrokeColor(colors.HexColor("#aaaaaa"))
    c.setFillColor(colors.HexColor("#f8f8f8"))
    c.roundRect(x, y, w, h, 5, fill=1, stroke=1)
    c.setFillColor(colors.HexColor("#222222"))
    c.setFont(title_font, 8)
    c.drawString(x + 8, y + h - 13, title)
    c.setFont(body_font, 6.5)
    yy = y + h - 24
    for line in lines:
        c.drawString(x + 8, yy, line)
        yy -= 9


def write_pdf(path: Path, inputs: EcojoinerInputs, d: EcojoinerDerived, *, font_dir: Optional[Path] = None) -> None:
    """Generate the one-page Letter landscape carpenter reference PDF."""
    if canvas is None:
        raise RuntimeError("ReportLab is not installed. Install with: pip install reportlab")

    title_font, body_font, symbol_font = _register_fonts(font_dir)
    lang = _pdf_lang(inputs)
    safe_title_font = _title_font_for(lang, title_font, body_font)

    page_w, page_h = landscape(letter)  # points
    c = canvas.Canvas(str(path), pagesize=landscape(letter))
    c.setTitle(f"Flatpack Ecojoiner v{DESIGN_VERSION}")

    margin = 28
    title_y = page_h - 34

    # Title and top vision statement.
    c.setFont(title_font, 20)
    c.setFillColor(colors.HexColor("#111111"))
    c.drawString(margin, title_y, f"Flatpack Ecojoiner v{DESIGN_VERSION}")

    para_width = 455  # roughly the width of the Long John drawing below
    style = ParagraphStyle(
        name="vision",
        fontName=body_font,
        fontSize=8.64,  # 20% larger than the original 7.2pt
        leading=10.8,
        textColor=colors.HexColor("#333333"),
    )
    p = Paragraph(html.escape(T(lang, "vision_statement")), style)
    p.wrapOn(c, para_width, 60)
    p.drawOn(c, margin, title_y - 58)  # 10pt more clearance below the title than before

    # Board-thickness banner, sitting above the Input variables box. Called
    # out on its own here (rather than left as a dimension line + arrows on
    # the Long John drawing below) since one banner reads faster than a
    # dimension line the reader has to trace back to a callout.
    thickness_box_h = 22
    thickness_box_gap = 6
    thickness_font_size = 9
    thickness_text = T(lang, "board_thickness", thickness=_ceil_mm(inputs.slat_thickness))
    thickness_text_w = c.stringWidth(thickness_text, safe_title_font, thickness_font_size)
    thickness_box_w = thickness_text_w + 16  # right-aligned to the same edge
    # as the Input variables / Derived dimensions boxes below, but sized to
    # fit its own (longer) sentence rather than sharing their fixed 155pt.
    thickness_box_x = page_w - margin - thickness_box_w

    # Input and derived boxes, kept compact. Shifted down from the page top
    # by the thickness banner's height so the two never overlap.
    box_y = page_h - 92 - thickness_box_h - thickness_box_gap
    input_lines = [
        T(lang, "wood", value=_ceil_mm(inputs.slat_thickness)),
        T(lang, "port_length_line", value=_ceil_mm(d.port_length)),
        T(lang, "bottle_diameter", value=_ceil_mm(inputs.port_height)),
        T(lang, "cap_line", value=_ceil_mm(inputs.cap_diameter)),
        T(lang, "collar_line", value=_ceil_mm(inputs.collar_diameter)),
        T(lang, "fit_clearance_line", value=_ceil_mm(inputs.fit_clearance)),
    ]
    derived_lines = [
        T(lang, "john_dim", length=_ceil_mm(d.john_length), height=_ceil_mm(d.john_height)),
        T(lang, "slot_width_line", value=_ceil_mm(d.slot_width)),
        T(lang, "std_slot_depth_line", value=_ceil_mm(d.standard_slot_depth)),
        T(lang, "master_slot_depth_line", value=_ceil_mm(d.master_slot_depth)),
        T(lang, "final_key_dim", length=_ceil_mm(d.final_key_length), width=_ceil_mm(d.final_key_width)),
        T(lang, "presser_dim", value=_ceil_mm(d.presser_diameter)),
    ]

    thickness_box_y = (box_y - 8) + 76 + thickness_box_gap
    c.setStrokeColor(colors.HexColor("#aaaaaa"))
    c.setFillColor(colors.HexColor("#f8f8f8"))
    c.roundRect(thickness_box_x, thickness_box_y, thickness_box_w, thickness_box_h, 5, fill=1, stroke=1)
    c.setFillColor(colors.HexColor("#111111"))
    c.setFont(safe_title_font, thickness_font_size)
    c.drawCentredString(
        thickness_box_x + thickness_box_w / 2,
        thickness_box_y + thickness_box_h / 2 - 3.5,
        thickness_text,
    )

    _rounded_rect_text(c, page_w - margin - 155, box_y - 8, 155, 76, T(lang, "input_variables_title"), input_lines, safe_title_font, body_font)
    derived_box_x, derived_box_y, derived_box_w = page_w - margin - 155, box_y - 94, 155
    _rounded_rect_text(c, derived_box_x, derived_box_y, derived_box_w, 76, T(lang, "derived_dimensions_title"), derived_lines, safe_title_font, body_font)

    # Notes, placed under the Derived dimensions box rather than at the foot
    # of the page so the John drawings can use the full page height.
    notes_style = ParagraphStyle(
        name="notes",
        fontName=body_font,
        fontSize=6,
        leading=7.4,
        textColor=colors.HexColor("#333333"),
    )
    notes_p = Paragraph(html.escape(T(lang, "notes")), notes_style)
    notes_p.wrapOn(c, derived_box_w, 60)
    notes_p.drawOn(c, derived_box_x, derived_box_y - 10 - notes_p.height)

    # Main drawing area. Scale is chosen to fill the available Letter page
    # space; the PDF is a reference, not a 1:1 tracing template. The SVG
    # export is the 1:1 cut file. The three Johns share one scale (derived
    # from the tallest constraint, vertical space) so they stay comparable,
    # and are spread evenly through the full column height instead of being
    # crammed into a small fixed-size block.
    left_pad = 80  # room for the rotated part title and the overall-height
    # dimension line, stacked to the left of each slat
    draw_x = margin + left_pad
    right_col_x = page_w - margin - 205  # Final Key / Presser column start

    content_top = page_h - 130
    content_bottom = 45  # the footer notes have moved up next to the Derived dimensions box
    n_rows = 3
    row_pitch = (content_top - content_bottom) / n_rows

    # Reserve space above each slat for the port-length/between-notch
    # dimension row and the slot-width dimension line, and below each slat
    # for the side-offset and overall-length dimension lines, so arrows never
    # collide with the geometry or the next row. The part title has moved to
    # a rotated label on the left of the slat, so it no longer needs room
    # above the row.
    top_pad = 30
    bottom_pad = 34
    slat_h_budget = row_pitch - top_pad - bottom_pad

    available_width = right_col_x - draw_x - 20
    scale = min(available_width / d.john_length, slat_h_budget / d.john_height)
    s = scale

    def sx(v): return v * s

    def draw_john(label, row_top, slot_depth, slots, hole_diam):
        x = draw_x
        y_top = row_top - top_pad
        y = y_top - sx(d.john_height)
        x_right = x + sx(d.john_length)
        c.setStrokeColor(colors.black)
        c.setFillColor(colors.white)
        c.setLineWidth(1)

        # Outer profile: bottom, left, and right edges are solid. The top
        # edge is drawn in segments that skip over each slot opening, since
        # the slots are notches cut into the top edge, not closed pockets -
        # a continuous line across them would misleadingly show them as
        # closed.
        c.line(x, y, x_right, y)
        c.line(x, y, x, y_top)
        c.line(x_right, y, x_right, y_top)
        slot_gaps = [
            (x + sx(cx - d.slot_width / 2), x + sx(cx + d.slot_width / 2))
            for cx in slots
        ]
        _draw_top_edge_with_gaps(c, x, y_top, x_right, slot_gaps)

        # Slots: left, right, and bottom only - no top line, since the slot
        # is open into the board's top edge, not a closed pocket.
        for cx in slots:
            slot_left = x + sx(cx - d.slot_width / 2)
            slot_right = x + sx(cx + d.slot_width / 2)
            slot_bottom = y_top - sx(slot_depth)
            c.line(slot_left, y_top, slot_left, slot_bottom)
            c.line(slot_right, y_top, slot_right, slot_bottom)
            c.line(slot_left, slot_bottom, slot_right, slot_bottom)

        # Center hole.
        c.circle(x + sx(d.john_length / 2), y + sx(d.john_height / 2), sx(hole_diam / 2), stroke=1, fill=0)
        c.setFillColor(colors.HexColor("#111111"))
        c.setFont(symbol_font, 9)
        c.drawCentredString(x + sx(d.john_length / 2), y + sx(d.john_height / 2) - 3, f"⌀{_ceil_mm(hole_diam)}")

        # Screw pilot holes. The left hole's label grows rightward and the
        # right hole's label grows leftward, back toward the hole, so
        # neither one runs past the slat's outer edge.
        screw_label = f"M6 (⌀{_ceil_mm(inputs.screw_diameter)}mm)"
        for i, hx in enumerate((d.screw_side_offset, d.john_length - d.screw_side_offset)):
            hcx, hcy = x + sx(hx), y + sx(d.screw_y_center)
            c.circle(hcx, hcy, sx(inputs.screw_diameter / 2), stroke=1, fill=0)
            c.setFillColor(colors.HexColor("#111111"))
            c.setFont(symbol_font, 6.5)
            if i == 0:
                c.drawString(hcx + 7, hcy + 2, screw_label)
            else:
                c.drawRightString(hcx - 7, hcy + 2, screw_label)

        # Part title, rotated 90 degrees and set to the left of the slat
        # rather than above it, so the vertical space above each row is free
        # for the Johns to be spaced comfortably apart.
        c.saveState()
        c.setFillColor(colors.HexColor("#111111"))
        c.setFont(title_font, 11)
        c.translate(x - 58, (y + y_top) / 2)
        c.rotate(90)
        c.drawCentredString(0, 0, label)
        c.restoreState()

        # Dimension lines for port length, the gap between the two notches,
        # slot width/depth, overall height, screw side offset, and overall
        # length, given generous clearance from the geometry so arrowheads,
        # witness lines, and text don't crowd each other or the title.
        slot_cx = slots[0]
        slot_left_mm = slot_cx - d.slot_width / 2
        slot_right_mm = slot_cx + d.slot_width / 2
        slot_left = x + sx(slot_left_mm)
        slot_right = x + sx(slot_right_mm)
        slot_cx_pt = x + sx(slot_cx)

        # Port length: the distance from the slat's side to the start of the
        # first notch. Between-notch span: the gap left between the two
        # notches, which seats the bottle body (its diameter).
        slot2_cx = slots[1]
        slot2_left_mm = slot2_cx - d.slot_width / 2
        port_length_mm = slot_left_mm
        between_notches_mm = slot2_left_mm - slot_right_mm
        slot2_left = x + sx(slot2_left_mm)
        port_row_y = y_top + 26
        _draw_dimension_line(
            c, x, port_row_y, slot_left, port_row_y, T(lang, "port_label", value=_ceil_mm(port_length_mm)), body_font, 6.5,
            ext1=(x, y_top), ext2=(slot_left, y_top),
        )
        _draw_dimension_line(
            c, slot_right, port_row_y, slot2_left, port_row_y, T(lang, "between_notches_label", value=_ceil_mm(between_notches_mm)), body_font, 6.5,
            ext1=(slot_right, y_top), ext2=(slot2_left, y_top),
        )

        _draw_dimension_line(
            c, slot_left, y_top + 9, slot_right, y_top + 9, T(lang, "slot_label", value=_ceil_mm(d.slot_width)), body_font, 6.5,
            ext1=(slot_left, y_top), ext2=(slot_right, y_top),
        )
        _draw_dimension_line(
            c, slot_cx_pt, y_top, slot_cx_pt, y_top - sx(slot_depth), f"{_ceil_mm(slot_depth)}mm", body_font, 6.5, rotate_label=True,
        )
        _draw_dimension_line(
            c, x - 14, y, x - 14, y_top, f"{_ceil_mm(d.john_height)}mm", body_font, 6.5, label_side="left",
            ext1=(x, y), ext2=(x, y_top),
        )
        _draw_dimension_line(
            c, x, y - 11, x + sx(d.screw_side_offset), y - 11, T(lang, "from_side_label"), body_font, 6.5,
            ext1=(x, y), ext2=(x + sx(d.screw_side_offset), y),
        )
        _draw_dimension_line(
            c, x, y - 27, x + sx(d.john_length), y - 27, f"{_ceil_mm(d.john_length)}mm", body_font, 6.5,
            ext1=(x, y), ext2=(x + sx(d.john_length), y),
        )

    long_slots = (d.long_end_span + inputs.slat_thickness / 2, d.john_length - d.long_end_span - inputs.slat_thickness / 2)
    little_slots = (d.little_end_span + inputs.slat_thickness / 2, d.john_length - d.little_end_span - inputs.slat_thickness / 2)

    draw_john("Long John x 6", content_top, d.standard_slot_depth, long_slots, inputs.cap_diameter)
    draw_john("Little John x 5", content_top - row_pitch, d.standard_slot_depth, little_slots, inputs.collar_diameter)
    draw_john("Master John x 1", content_top - 2 * row_pitch, d.master_slot_depth, little_slots, inputs.collar_diameter)

    # Right-side parts: Final Key and Presser. Lowered from the top of their
    # column (they used to sit right under the Derived-dimensions notes,
    # leaving a large empty gap between them and the footer) so they split
    # the column's leftover vertical space more evenly.
    right_x = page_w - margin - 205
    right_y = 170

    c.setFont(title_font, 9)
    c.drawString(right_x, right_y + 118, "Final Key x 4")
    fk_scale = min(1.0, 190 / d.final_key_length)
    c.setStrokeColor(colors.black)
    c.setLineWidth(1)
    c.rect(right_x, right_y + 90, d.final_key_length * fk_scale, d.final_key_width * fk_scale, fill=0, stroke=1)
    _draw_dimension_line(
        c, right_x, right_y + 74, right_x + d.final_key_length * fk_scale, right_y + 74, f"{_ceil_mm(d.final_key_length)}mm", body_font, 5,
        ext1=(right_x, right_y + 90), ext2=(right_x + d.final_key_length * fk_scale, right_y + 90),
    )
    _draw_dimension_line(
        c, right_x - 7, right_y + 90, right_x - 7, right_y + 90 + d.final_key_width * fk_scale, f"{_ceil_mm(d.final_key_width)}mm", body_font, 5, label_side="left",
        ext1=(right_x, right_y + 90), ext2=(right_x, right_y + 90 + d.final_key_width * fk_scale),
    )

    # Presser top view and side/section view directly below it.
    p_top_cx = right_x + 58
    p_top_cy = right_y + 10
    p_r = 22
    c.setFont(title_font, 9)
    c.drawString(right_x, p_top_cy + 46, "Presser x 12")
    c.setStrokeColor(colors.black)
    c.setLineWidth(1)
    c.circle(p_top_cx, p_top_cy, p_r, stroke=1, fill=0)
    c.circle(p_top_cx, p_top_cy, p_r * d.presser_through_hole_diameter / d.presser_diameter, stroke=1, fill=0)
    c.setDash(2, 2)
    c.circle(p_top_cx, p_top_cy, p_r * d.presser_nut_recess_diameter / d.presser_diameter, stroke=1, fill=0)
    c.setDash()
    _draw_dimension_line(
        c, p_top_cx - p_r, p_top_cy - p_r - 8, p_top_cx + p_r, p_top_cy - p_r - 8, f"⌀{_ceil_mm(d.presser_diameter)}mm", body_font, 5,
        ext1=(p_top_cx - p_r, p_top_cy), ext2=(p_top_cx + p_r, p_top_cy),
    )
    c.setFont(body_font, 6)
    c.drawString(p_top_cx + p_r + 12, p_top_cy + 8, T(lang, "through_hole_label", value=_ceil_mm(d.presser_through_hole_diameter)))
    c.drawString(p_top_cx + p_r + 12, p_top_cy - 2, T(lang, "nut_recess_label", diam=_ceil_mm(d.presser_nut_recess_diameter), depth=_ceil_mm(d.presser_nut_recess_depth)))

    # Side/section view under top view. Uses the same points-per-mm scale as
    # the top view (derived from p_r / presser radius) so the two views
    # depict the same physical part at matching sizes - the section's width
    # equals the top view's diameter, and its through-hole/recess widths
    # match the top view's hole/recess circles, rather than being drawn at
    # unrelated fixed sizes.
    presser_scale = p_r / (d.presser_diameter / 2)
    side_w = d.presser_diameter * presser_scale
    side_h = d.presser_thickness * presser_scale
    side_x = p_top_cx - side_w / 2
    side_y = p_top_cy - 62
    c.setStrokeColor(colors.black)
    c.setLineWidth(1)
    c.rect(side_x, side_y, side_w, side_h, fill=0, stroke=1)
    # Through hole in section.
    hole_w = d.presser_through_hole_diameter * presser_scale
    c.rect(p_top_cx - hole_w / 2, side_y, hole_w, side_h, fill=0, stroke=1)
    # Recess from top.
    recess_w = d.presser_nut_recess_diameter * presser_scale
    recess_h = d.presser_nut_recess_depth * presser_scale
    c.rect(p_top_cx - recess_w / 2, side_y + side_h - recess_h, recess_w, recess_h, fill=0, stroke=1)
    _draw_dimension_line(
        c, side_x + side_w + 24, side_y, side_x + side_w + 24, side_y + side_h, f"{_ceil_mm(d.presser_thickness)}mm", body_font, 5,
        ext1=(side_x + side_w, side_y), ext2=(side_x + side_w, side_y + side_h),
    )
    _draw_dimension_line(
        c, p_top_cx + recess_w / 2 + 6, side_y + side_h - recess_h, p_top_cx + recess_w / 2 + 6, side_y + side_h, f"{_ceil_mm(d.presser_nut_recess_depth)}mm", body_font, 5,
        ext1=(p_top_cx + recess_w / 2, side_y + side_h - recess_h), ext2=(p_top_cx + recess_w / 2, side_y + side_h),
    )

    # Credit box, sized to hug its two lines of text rather than leaving a
    # tall band of empty space below them (the box used to be 44pt tall for
    # ~20pt of actual text).
    credit_h = 32
    credit_line2_y = 15
    credit_line1_y = credit_line2_y + 11
    c.setStrokeColor(colors.HexColor("#aaaaaa"))
    c.setFillColor(colors.HexColor("#f8f8f8"))
    c.roundRect(margin, 8, page_w - 2 * margin, credit_h, 5, fill=1, stroke=1)
    c.setFillColor(colors.HexColor("#222222"))
    c.setFont(body_font, 6.5)
    c.drawString(margin + 8, credit_line1_y, T(lang, "license_statement"))
    c.drawString(margin + 8, credit_line2_y, T(lang, "version_credit", version=DESIGN_VERSION))

    c.showPage()
    c.save()


# ---------------------------------------------------------------------------
# Generation orchestration
# ---------------------------------------------------------------------------

def generate_exports(
    inputs: EcojoinerInputs,
    output_root: Path,
    public_url_prefix: str = "/ecojoiner_exports",
    font_dir: Optional[Path] = None,
    dry_run: bool = False,
) -> Dict[str, object]:
    """Validate inputs and write requested export files.

    Returns a dict that can be converted directly to JSON for the frontend.

    With dry_run=True nothing is written to disk. The caller still gets the
    validation result and every derived dimension, which is what the website
    needs to show a confirmation screen before the user commits to a download.
    """

    errors = validate_inputs(inputs)
    if errors:
        return {"ok": False, "errors": errors}

    d = derive_dimensions(inputs)
    slug = make_job_slug(inputs, d)

    if dry_run:
        return {
            "ok": True,
            "dry_run": True,
            "design_version": DESIGN_VERSION,
            "license": LICENSE_ID,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "job_slug": slug,
            "inputs": asdict(inputs),
            "derived": asdict(d),
            "files": [],
        }

    job_dir = output_root / slug
    job_dir.mkdir(parents=True, exist_ok=True)

    files: List[GeneratedFile] = []

    # SCAD is useful both as a user download and as an intermediate file for
    # later OpenSCAD CLI generation of STL if you add that format. DXF is
    # written directly by write_dxf() below, not derived from this file.
    if "scad" in inputs.formats:
        scad_path = job_dir / f"{slug}.scad"
        write_scad(scad_path, inputs, d)
        files.append(GeneratedFile("scad", "OpenSCAD source", str(scad_path), f"{public_url_prefix}/{slug}/{scad_path.name}"))

    if "svg" in inputs.formats:
        svg_path = job_dir / f"{slug}_full_set_1to1.svg"
        write_svg(svg_path, inputs, d, full_set=True)
        files.append(GeneratedFile("svg", "1:1 SVG full-set cutting file", str(svg_path), f"{public_url_prefix}/{slug}/{svg_path.name}"))

        preview_svg_path = job_dir / f"{slug}_one_each_1to1.svg"
        write_svg(preview_svg_path, inputs, d, full_set=False)
        files.append(GeneratedFile("svg", "1:1 SVG one-each layout", str(preview_svg_path), f"{public_url_prefix}/{slug}/{preview_svg_path.name}"))

    if "dxf" in inputs.formats:
        dxf_path = job_dir / f"{slug}_full_set_1to1.dxf"
        write_dxf(dxf_path, inputs, d, full_set=True)
        files.append(GeneratedFile("dxf", "1:1 DXF full-set cutting file", str(dxf_path), f"{public_url_prefix}/{slug}/{dxf_path.name}"))

        preview_dxf_path = job_dir / f"{slug}_one_each_1to1.dxf"
        write_dxf(preview_dxf_path, inputs, d, full_set=False)
        files.append(GeneratedFile("dxf", "1:1 DXF one-each layout", str(preview_dxf_path), f"{public_url_prefix}/{slug}/{preview_dxf_path.name}"))

    if "pdf" in inputs.formats:
        pdf_path = job_dir / f"{slug}_carpenter_sheet.pdf"
        write_pdf(pdf_path, inputs, d, font_dir=font_dir)
        files.append(GeneratedFile("pdf", "Letter PDF carpenter sheet", str(pdf_path), f"{public_url_prefix}/{slug}/{pdf_path.name}"))

    manifest = {
        "ok": True,
        "design_version": DESIGN_VERSION,
        "license": LICENSE_ID,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "job_slug": slug,
        "inputs": asdict(inputs),
        "derived": asdict(d),
        "files": [asdict(f) for f in files],
    }

    manifest_path = job_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    manifest["manifest_path"] = str(manifest_path)
    manifest["manifest_url"] = f"{public_url_prefix}/{slug}/manifest.json"

    return manifest


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate Ecojoiner v3.2 PDF, SCAD, and SVG exports.")
    p.add_argument("--slat-thickness", type=float, default=12.0, help="Wood thickness in mm.")
    p.add_argument("--cap-diameter", type=float, default=32.0, help="Bottle cap diameter in mm.")
    p.add_argument("--collar-diameter", type=float, default=32.0, help="Bottle collar diameter in mm.")
    p.add_argument("--taper-height", type=float, default=60.0, help="Bottle taper height in mm. Used with port allowance.")
    p.add_argument("--port-length", type=float, default=None, help="Optional direct port length in mm. Overrides taper height.")
    p.add_argument("--port-allowance", type=float, default=DEFAULT_PORT_ALLOWANCE_MM, help="Extra seating allowance added to taper height.")
    p.add_argument("--port-height", type=float, default=85.0, help="Bottle diameter / port height in mm.")
    p.add_argument("--port-fit-mm", type=float, default=0.0, help="Connection fit offset in mm, added to port height (negative = tighter).")
    p.add_argument("--bottle-volume-l", type=float, default=1.5, help="Bottle volume in litres, used for naming/stats.")
    p.add_argument("--bottle-brand", type=str, default="generic", help="Bottle brand, used for naming/stats.")
    p.add_argument("--screw-diameter", type=float, default=4.5, help="M6 pilot-hole cut diameter in mm.")
    p.add_argument("--fit-clearance", type=float, default=0.20, help="Slot clearance in mm.")
    p.add_argument("--formats", type=str, default="pdf,scad,svg", help="Comma-separated formats: pdf,scad,svg.")
    p.add_argument("--job-id", type=str, default="", help="Optional job id for stable file naming.")
    p.add_argument("--output-dir", type=Path, default=Path("public/ecojoiner_exports"), help="Output directory root.")
    p.add_argument("--public-url-prefix", type=str, default="/ecojoiner_exports", help="URL prefix matching Express static routing.")
    p.add_argument("--font-dir", type=Path, default=None, help="Optional directory containing Arvo/Mulish fonts.")
    p.add_argument("--json", type=Path, default=None, help="Optional JSON file containing input fields from the frontend.")
    p.add_argument("--dry-run", action="store_true", help="Validate and derive dimensions without writing any files.")
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)

    if args.json:
        data = json.loads(args.json.read_text(encoding="utf-8"))
        inputs = parse_inputs_from_dict(data)
    else:
        inputs = EcojoinerInputs(
            slat_thickness=args.slat_thickness,
            cap_diameter=args.cap_diameter,
            collar_diameter=args.collar_diameter,
            taper_height=args.taper_height,
            port_length=args.port_length,
            port_allowance=args.port_allowance,
            port_height=args.port_height + args.port_fit_mm,
            bottle_volume_l=args.bottle_volume_l,
            bottle_brand=args.bottle_brand,
            screw_diameter=args.screw_diameter,
            fit_clearance=args.fit_clearance,
            formats=tuple(x.strip().lower() for x in args.formats.split(",") if x.strip()),
            job_id=args.job_id,
        )

    result = generate_exports(
        inputs,
        output_root=args.output_dir,
        public_url_prefix=args.public_url_prefix.rstrip("/"),
        font_dir=args.font_dir,
        dry_run=args.dry_run,
    )

    print(json.dumps(result, indent=2))
    return 0 if result.get("ok") else 2


if __name__ == "__main__":
    raise SystemExit(main())
